import { debounce } from "@/utils";

export default {
  data() {
    return {
      imagesArr: [
        {
          coordinates: [658156.508648, 3561258.724081],
          img: require("@/assets/images/images1.png"),
          bgImg: require("@/assets/images/img_mark.png"),
          id: 1,
          type: "a2PSL",
        },
        {
          coordinates: [657438.108894, 3561171.850467],
          img: require("@/assets/images/images2.png"),
          bgImg: require("@/assets/images/img_mark.png"),
          id: 2,
          type: "a2PSL",
        },
        {
          coordinates: [655504.880255, 3561880.473045],
          img: require("@/assets/images/images3.png"),
          bgImg: require("@/assets/images/img_mark.png"),
          id: 3,
          type: "a2SX",
        },
        {
          coordinates: [658172.853606, 3562269.558025],
          img: require("@/assets/images/images4.png"),
          bgImg: require("@/assets/images/img_mark.png"),
          id: 4,
          type: "a2SX",
        },
        {
          coordinates: [659270.46336, 3561907.794993],
          img: require("@/assets/images/images5.png"),
          bgImg: require("@/assets/images/img_mark.png"),
          id: 5,
          type: "a2DS",
        },
        {
          coordinates: [659590.65757, 3561279.9415],
          img: require("@/assets/images/images6.png"),
          bgImg: require("@/assets/images/img_mark.png"),
          id: 6,
          type: "a2DS",
        },
        {
          coordinates: [654664.582493, 3561950.881577],
          img: require("@/assets/images/images7.png"),
          bgImg: require("@/assets/images/img_mark.png"),
          id: 7,
          type: "a1GJ",
        },
        {
          coordinates: [662340.928774, 3560368.252009],
          img: require("@/assets/images/images8.png"),
          bgImg: require("@/assets/images/img_mark.png"),
          id: 8,
          type: "a1GJ",
        },
      ],

      areaLineFilterVals: [
        {
          "Test:cad_line": "08-01北站快速路征",
          "Test:cad_area": "08-01北站快速路征",
        },

        {
          "Test:cad_line": "06-06-01地铁",
          "Test:cad_area": "06-06-01地铁",
        },
        {
          "Test:cad_line": "02-02规划路网（双",
          "Test:cad_area": "02-02规划路网（双",
        },
      ],

      treeData: [
        {
          id: 80,
          label: "骨架路网",
          literal: "01骨架路网",
          fillColor: "RGB(0,0,255)",
          strokeColor: "RGB(0,0,255)",
          width: "4",
          layerName: "Test:lines0822",
          filterKey: "layer",
        },
        {
          id: 81,
          label: "功能定位",
          children: [
            {
              id: 811,
              label: "近期线位",
              literal: "近期线位",
              fillColor: "#FF0000",
              strokeColor: "#FF0000",
              width: "4",
              layerName: "Test:jqxw",
              filterKey: "layerName",
              dashOffset: "10",
              dasharray: [10, 10],
            },
            {
              id: 812,
              label: "现状线位",
              literal: "现状线位",
              fillColor: "#1CB151",
              strokeColor: "#1CB151",
              width: "4",
              layerName: "Test:xzxw",
              filterKey: "layerName",
            },
            {
              id: 813,
              label: "远期线位",
              literal: "远期线位",
              fillColor: "#0000FF",
              strokeColor: "#0000FF",
              width: "4",
              layerName: "Test:yqxw",
              filterKey: "layerName",
              dashOffset: "0",
              dasharray: [10, 10],
            },
          ],
        },

        {
          id: 83,
          label: "建设条件",
          children: [
            {
              id: 831,
              label: "1浦泗路现状",
              layerName: "Test:lines0822",
              filterKey: "layer",
            },
            {
              id: 832,
              label: "2规划铁路",
              layerName: "Test:lines0822",
              filterKey: "layer",
              children: [
                {
                  id: 8321,
                  label: "北沿江高铁",
                  literal: "03-02-01北沿江高铁",
                  fillColor: "RGB(0,189,189)",
                  strokeColor: "RGB(0,189,189)",
                  width: "1",
                },
                {
                  id: 8322,
                  label: "宁淮城际铁路",
                  literal: "03-02-02宁淮城际铁",
                  fillColor: "RGB(0,189,189)",
                  strokeColor: "RGB(0,189,189)",
                  width: "1",
                },
                {
                  id: 8323,
                  label: "普速系统改建",
                  literal: "03-02-03普速系统改",
                  fillColor: "RGB(0,189,189)",
                  strokeColor: "RGB(0,189,189)",
                  width: "1",
                },
              ],
            },

            {
              id: 833,
              label: "3城市轨道交通",
              layerName: "Test:lines0822",
              filterKey: "layer",
              literal: "03-03城市轨道交通",
              fillColor: "RGB(255,0,255)",
              strokeColor: "RGB(255,0,255)",
            },

            {
              id: 834,
              label: "4水系及文物",
              layerName: "Test:area0822",
              filterKey: "layer",
              children: [
                {
                  id: 8341,
                  label: "中心河",
                  literal: "03-04-01中心河",
                  fillColor: "RGB(0,191,255)",
                  strokeColor: "RGB(0,191,255)",
                  width: "1",
                },
                {
                  id: 8343,
                  label: "东一河",
                  literal: "03-04-02东一河",
                  fillColor: "RGB(0,191,255)",
                  strokeColor: "RGB(0,191,255)",
                  width: "1",
                },
                {
                  id: 8344,
                  label: "朱家山河",
                  literal: "03-04-03朱家山河",
                  fillColor: "RGB(0,191,255)",
                  strokeColor: "RGB(0,191,255)",
                  width: "1",
                },
                {
                  id: 8345,
                  label: "后河",
                  literal: "03-04-04后河",
                  fillColor: "RGB(0,191,255)",
                  strokeColor: "RGB(0,191,255)",
                  width: "1",
                },
                {
                  id: 8346,
                  label: "规划河道",
                  literal: "03-04-05规划河道",
                  fillColor: "RGB(0,191,255)",
                  strokeColor: "RGB(0,191,255)",
                  width: "1",
                },
              ],
            },

            {
              id: 835,
              label: "5地上杆线和地下管线",
              layerName: "Test:lines0822",
              filterKey: "layer",
              literal: "03-05地上杆线及地",
              fillColor: "RGB(255,255,0)",
              strokeColor: "RGB(255,255,0)",
              width: "4",
            },
          ],
        },

        {
          id: 84,
          label: "起终点研究",
          layerName: "Test:area0822",
          filterKey: "layer",
          children: [
            {
              id: 841,
              label: "基本农田",
              literal: "04基本农田",
              fillColor: "RGB(0,255,0)",
              strokeColor: "RGB(0,255,0)",
              width: "1",
            },
          ],
        },

        {
          id: 85,
          label: "规划路网",
          layerName: "Test:area0822",
          filterKey: "layer",
          children: [
            {
              id: 851,
              label: "北站快速路",
              literal: "05-01北站快速路",
              fillColor: "RGB(255,0,255)",
              strokeColor: "RGB(255,0,255)",
              width: "1",
            },
            {
              id: 852,
              label: "朱家山河路",
              literal: "05-02朱家山河路",
              fillColor: "RGB(129,0,0)",
              strokeColor: "RGB(129,0,0)",
              width: "1",
            },
            {
              id: 853,
              label: "站南一路",
              literal: "05-03站南一路",
              fillColor: "RGB(0,0,255)",
              strokeColor: "RGB(0,0,255)",
              width: "1",
            },
            {
              id: 854,
              label: "站南二路",
              literal: "05-04站南二路",
              fillColor: "RGB(129,0,0)",
              strokeColor: "RGB(129,0,0)",
              width: "1",
            },
            {
              id: 855,
              label: "站西路",
              literal: "05-05站西路",
              fillColor: "RGB(0,0,255)",
              strokeColor: "RGB(0,0,255)",
              width: "1",
            },
            {
              id: 856,
              label: "西快线",
              literal: "05-06西快线",
              fillColor: "RGB(255,0,255)",
              strokeColor: "RGB(255,0,255)",
              width: "1",
            },
          ],
        },

        {
          id: 86,
          label: "涉铁节点道路工程",
          literal: "06涉铁节点道路工",
          layerName: "Test:area0822",
          filterKey: "layer",
          fillColor: "RGB(0,0,255)",
          strokeColor: "RGB(0,0,255)",
          width: "1",
        },
        {
          id: 87,
          label: "南京北站站台",
          literal: "07南京北站站房",
          layerName: "Test:area0822",
          filterKey: "layer",
          fillColor: "RGB(255,0,0)",
          strokeColor: "RGB(255,0,0)",
          width: "1",
        },
      ],
    };
  },
  methods: {},
};
